apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: c2b8cutrn-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: c2b8cutrn-python 
  name: c2b8cutrn-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: c2b8cutrn-python 
